# Generated by Django 3.1.5 on 2021-01-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
