# Generated by Django 3.1.5 on 2021-01-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
