# Generated by Django 3.1.5 on 2021-01-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20210128_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
