# Generated by Django 3.1.5 on 2021-01-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20210128_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='author',
            new_name='created_by',
        ),
    ]
